matlabroot = '/usr/local/MATLAB/R2019a';

digitDatasetPath = fullfile(matlabroot,'toolbox','nnet', ...
    'nndemos','nndatasets','DigitDataset');
imds = imageDatastore(digitDatasetPath, ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

imds.ReadSize = 50;
rng(0);
imds = shuffle(imds);

[imdsTrain,imdsVal,imdsTest] = splitEachLabel(imds,0.95,0.025);
dsTrainNoisy = transform(imdsTrain,@addNoise);
dsValNoisy = transform(imdsVal,@addNoise);
dsTestNoisy = transform(imdsTest,@addNoise);

dsTrain = combine(dsTrainNoisy,imdsTrain);
dsVal = combine(dsValNoisy,imdsVal);
dsTest = combine(dsTestNoisy,imdsTest);

dsTrain = transform(dsTrain,@commonPreprocessing);
dsVal = transform(dsVal,@commonPreprocessing);
dsTest = transform(dsTest,@commonPreprocessing);

dsTrain = transform(dsTrain,@augmentImages);

imageLayer = imageInputLayer([32,32,1]);
encodingLayers = [ ...
    convolution2dLayer(4,8,'Padding','same','Name','convlayer1'), ...
    batchNormalizationLayer('Name','BN1'), ...
    reluLayer, ...
    maxPooling2dLayer(2,'Padding','same','Stride',2,'Name','maxlayer1'), ...
    convolution2dLayer(4,16,'Padding','same','Name','convlayer2'), ...
    batchNormalizationLayer('Name','BN2'), ...
    reluLayer, ...
    maxPooling2dLayer(2,'Padding','same','Stride',2,'Name','maxlayer2'), ...
    convolution2dLayer(4,32,'Padding','same','Name','convlayer3'), ...
    batchNormalizationLayer('Name','BN3'), ...
    reluLayer, ...
    maxPooling2dLayer(2,'Padding','same','Stride',2,'Name','maxlayer3')];

decodingLayers = [ ...
    createUpsampleTransponseConvLayer(2,32,'tconvlayer1'), ...
    reluLayer, ...
    createUpsampleTransponseConvLayer(2,16,'tconvlayer2'), ...
    reluLayer, ...
    createUpsampleTransponseConvLayer(2,8,'tconvlayer3'), ...
    reluLayer, ...
    convolution2dLayer(3,1,'Padding','same','Name','convlayer4'), ...
    clippedReluLayer(1.0), ...
    regressionLayer];

layers = [imageLayer,encodingLayers,decodingLayers];

options = trainingOptions('adam', ...
    'MaxEpochs',100, ...
    'MiniBatchSize',imds.ReadSize, ...
    'ValidationData',dsVal, ...
    'Shuffle','never', ...
    'Plots','training-progress', ...
    'LearnRateDropFactor',0.5, ...
    'LearnRateDropPeriod',20, ...
    'InitialLearnRate',0.004, ...
    'Verbose',false);

fprintf("Training Started\n");
net = trainNetwork(dsTrain,layers,options);
save net;
fprintf("net Saved\n");
